[package]
name = "lofi_suicidalteddy"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = "0.14"
glib = "0.14"
gio = "0.14"
gstreamer = "0.20"
gstreamer-base = "0.20"
gstreamer-audio = "0.20"
gstreamer-player = "0.20"
rand = "0.8"
